lib/content/content.go
--
Only the first time calling the getProvider function.
It is possible to prevent the allocator to run every time.
=> Eliminate unnecessary memory allocation.

cmd/fanlin/main.go, lib/conf/conf.go, lib/handler/handler.go
fanlin wasn't able to output stacktrace.
because, it was added to the renovation.
* `debug_log_path` option
=> output stacktrace

cmd/fanlin/main.go, lib/conf/conf.go, lib/content/web/web.go
Can be setting timeout duration.
It is defined of `backeend_request_timeout` param.
Format conforms to the duration format of go.
The default timeout duration is 10 seconds as usual.
ex. `{"backeend_request_timeout": "1h30m"}`
And I change using default http client.
=> timeout setting and use default http client in go.

README.ja.md, README.md, lib/content/content.go
When alias is like `alias/a/b` and `alias/a`, the provider may not be selected properly.
Added priority to metadata and sort by that.
=> Add to sort providers by priority

lib/content/s3/s3.go, lib/content/source.go
Buffering images on file complicates deletion timing.
The deletion timing was too early this time.
Change from file buffer to memory buffer.
=> fix file buffer in s3 content.

README.ja.md, README.md, lib/content/s3/s3.go, lib/content/s3/s3_test.go
Enable access to S3 from servers (ON-PREMISES server, etc.) without ACL.
By define the privider like bellow,  and add ENV variables of `AWS_ACCESS_KEY_ID` AND `AWS_SECRET_ACCESS_KEY`, you can download files from private S3 buckets from ON-PREMISES servers.
```
{   
...
"alias/3" : {
"type" : "s3",
"src" : "s3://bucket/path",
"region" : "ap-northeast-1",
"priority" : 30,
"use_env_credential": true
}
...
}
```
=> Add aws credentials for s3

README.ja.md, README.md
READMEにログを標準出力に出力することができる旨を追記する
resolve #40 
Thanks to @supercaracal, I learned that logs can be output to stdout.
I added it to the README as it would be useful.
=> Add a note to README that logs can be output to standard output

.goreleaser.yaml
The following job was failed in CI.
https://github.com/livesense-inc/fanlin/actions/runs/7244252101/job/19732285416
> line 22: field replacements not found in type config.Archive
It seems that the directive was deleted from GoReleaser settings. On second thought, I think we don't have to rename executable files.
=> ci: remove an obsolete directive from GoReleaser settings

.goreleaser.yaml
https://github.com/livesense-inc/fanlin/actions/runs/7244447066/job/19732789438
> error=build for fanlin does not contain a main function
* #49
* #50
=> ci: add a main.go path to the setting of GoReleaser

.github/workflows/release.yaml
Since we depend on glibc for the WebP conversion, we can't disable cgo. There may be an error to execute binary when glibc versions are different between build-environment and execute-environment. So I added a step to the release workflow to be able to recognize the glibc version in build-environment.
=> ci: print glibc version in the release workflow

.gitignore, cmd/fanlin/main.go, go.mod, go.sum, lib/conf/conf.go, lib/conf/conf_test.go, lib/test/test_conf.json
I'd say that a feature of limiting request concurrency is a nice-to-have option for the stability.
* https://cs.opensource.google/go/x/net/+/master:netutil/listen.go
* https://github.com/golang/go/blob/d49a14c6092ba30d0afbdaa06a24016ff1fe2a82/src/net/http/server.go#L3258-L3291
=> Add max-clients option

cmd/fanlin/main.go, lib/conf/conf.go, lib/conf/conf_test.go, lib/test/test_conf.json, lib/test/test_conf3.json, lib/test/test_conf4.json
It looks to me that the following options were aggregated to the `providers` directive. Correct me if I'm wrong.
* `local_image_path`
* `s3_bucket_name`
* `s3_region`
Also, I'm not pretty sure how the `externals` option effects this application. Either way, there were no implementation for it.
=> Remove not implemented options

.github/workflows/test.yml, .gitignore, Makefile, lib/handler/handler_test.go, lib/test/helper.go, lib/test/test_conf9.json
I added benchmark and profiling facilities to get a proof of a performance tuning. Also I set the both to a workflow in CI. I think we became to be able to review tunings were whether legit or not. As a context, I have a plan to try to lessen load of GC by using [sync.Pool](https://pkg.go.dev/sync#Pool) for some buffers in the future.
=> Add benchmark and profiling facilities

cmd/fanlin/main.go, lib/conf/conf.go, lib/conf/conf_test.go, lib/handler/handler_test.go
```
$ make run
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -ldflags="-s -w" -trimpath -tags timetzdata -o cmd/fanlin/server cmd/fanlin/main.go
open /etc/fanlin.json: no such file or directory
open /etc/fanlin.cnf: no such file or directory
open /etc/fanlin.conf: no such file or directory
open /usr/local/etc/fanlin.json: no such file or directory
open /usr/local/etc/fanlin.cnf: no such file or directory
open /usr/local/etc/fanlin.conf: no such file or directory
open /usr/local/fanlin/fanlin.json: no such file or directory
open /usr/local/fanlin.json: no such file or directory
open /usr/local/fanlin.conf: no such file or directory
read configure. : /home/kasuga/vcs/fanlin/fanlin.json
```
```
$ make run
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -ldflags="-s -w" -trimpath -tags …
```
=> Prevent printing verbose and too much information at initialization

cmd/fanlin/main.go, lib/content/content.go, lib/content/content_test.go, lib/handler/handler.go, lib/handler/handler_test.go, lib/test/test_conf8.json
The `providers` global variable in the content package is written once and read by the main handler which is called concurrently by each requests. Thus there is a race condition. It can be reproduced with a parallel unit test. So I think it should be kept data initialized in advance.
=> Fix a race condition

lib/conf/conf.go, lib/content/web/web_test.go, lib/handler/handler.go
I'll close this pull request if there is a rational reason to use `panic` at error handlings.
=> Use boilerplates instead of using panic at error handlings

README.ja.md, README.md
* Remove explicit Go version from README.md, mention `go.mod` instead
* Remove wording of "native Go" because it's no longer true
* e.g. WebP and AVIF formats support needs C libraries
=> Update readme file

.dockerignore, .github/workflows/release.yaml, .gitignore, Dockerfile, cmd/fanlin/sample-conf-container.json, compose.yaml
Since we supports WebP and AVIF formats, our build steps are a bit awkward. So I'd say that it would be better to publish the container image as a base image to the publish repository so that users don't need to bake their own images from scratch. And the container image size is approximately 50 MB.
=> Publish container image

.dockerignore, .gitignore, Makefile, compose.yaml, lib/content/s3/s3.go, lib/content/s3/s3_test.go
This pull request makes our AWS S3 client able to access local mock with [MinIO](https://github.com/minio/minio). And it fixes a bug related to a prefix in a object key.
Also, this is a bit off topic, but I have no idea yet how to improve current behavior which builds client every time per request. I think it needs breaking changes for config specification. The client is Goroutine safe.
=> Add a functionality for the testing of the S3 provider with MinIO on local and fix a bug

lib/handler/handler.go
This pull request fixes two things as follows:
* Remove `f_encode` metrics from server timing
* Because we directly write encode data into ResponseWriter, we are no longer able to measure the metrics before sending response body.
* #65
* The above modification is leading the following bug:
* > write: broken pipe
* > http: superfluous response.WriteHeader call from main.main.Middleware.func4.1.1 (middleware.go:55)
* Rename `f_decode` metrics with `f_process` and rename related method too
* Because the function does decode and resizing.
=> Fix a bug related to server-timing header

cmd/fanlin/main.go, lib/content/content.go, lib/handler/handler.go, lib/image/image.go
If a content is not found, fanlin returns a fallback image. It is loaded from disk every single time. I'd say that it would be better to cache it before server started.
=> Cache 404 image in memory on boot

cmd/fanlin/main.go, lib/conf/conf.go, lib/conf/conf_test.go, lib/test/test_conf.json
I'd say that the timeout settings is nice-to-have for the consideration of performance or malicious attack. The behavior is as is if there is no specification in the setting. So this modification is backward compatible.
https://pkg.go.dev/net/http#Server
=> Add server-side timeout option

lib/handler/handler.go
I'm seeing an error in our staging environment as follows:
> write: broken pipe
```mermaid
graph TD
client(Client)
cdn(CDN)
lb(Load Balancer)
fanlin(Fanlin)
client-->cdn
cdn-->client
cdn-->lb
lb-->cdn
lb-->fanlin
fanlin--error-->lb
```
It seems that the error has not been solved by the following fix.
* #85
I'm not pretty sure why the error was occurred, but I suspect that the following fix was a bad idea.
* #65
So this pull request reverts the above modification.
=> Revert a modification which writes encode data to the response directly, use buffer instead 

go.mod, go.sum, lib/handler/handler.go, lib/handler/handler_test.go, lib/image/image.go, lib/image/image_test.go
The following process is too slow. It spends lots of cpu time and memory allocation. It looks like a bottleneck.
https://github.com/livesense-inc/fanlin/blob/45a1655871dda0fa9b19840888af028705d93b78/lib/image/image.go#L336
The above process depends on the following library. Unfortunately, the last update is a decade ago.
https://github.com/BurntSushi/graphics-go
CPU
```
flat  flat%   sum%        cum   cum%
280ms 17.95% 17.95%      280ms 17.95%  github.com/nfnt/resize.resizeRGBA
220ms 14.10% 32.05%      730ms 46.79%  github.com/BurntSushi/graphics-go/graphics/interp.bilinearGeneral
150ms  9.62% 41.67%      230ms 14.74%  runtime.mallocgc
70ms  4.49% 46.15%       70ms  4.49%  image/color.YCbCr.RGBA
70ms  4.49% 50.64%      300ms 19.23%  image/jpeg.(*decoder).processSOS
70ms  4.49% 55.13% …
```
=> Use gift, which makes us 3 times faster

lib/content/s3/s3.go
https://tsak.dev/posts/aws-sdk-suppress-checksum-warning/
> WARN Response has no supported checksum. Not validating response payload.
This is just a noise for us.
=> Suppress an AWS S3 SDK checksum support warning

lib/handler/handler.go
Since the following pull request got rid of panic handlings, I think the stacktrace information is no longer needed in log.
* #73
=> Remove stacktrace from log

README.ja.md, README.md
Our fanlin requires "leading slash" in the path for the routing. I found that an example setting in readme was wrong. Although it would be better to be complementary by internal process, I fixed the example so far.
=> docs: fix wrong example setting in readme

lib/handler/handler.go, lib/image/image.go, lib/query/query.go, lib/query/query_test.go
Although I'm not pretty sure whether there is demand for these transformation or not, I'd say that they are nice-to-have features as an image-processing web server.
`40ms` (approximately `+0ms`)
`43ms`(approximately `+3ms`)
=> feat: add grayscale and inverse parameters to query

go.mod, go.sum
I added nil checks in the following library to prevent panic errors. So I bumped the version to the latest.
https://github.com/livesense-inc/go-lcms
=> fix: bump go-lcms version from 0.1.0 to 1.0.0

README.ja.md, README.md
https://deepwiki.com/livesense-inc/fanlin
DeepWiki says:
> Add a badge to this wiki in the repo's README file to auto refresh the wiki weekly with the latest code.
This pull request adds a badge for DeepWiki to README files so that the document generated by DeepWiki is kept to be fresh.
=> docs: add a badge for DeepWiki
